- name: Get started
  hosts: localhost
  become: true
  tasks:
  - name: Install zsh
    pacman: name=zsh
  - name: Change shell
    shell: chsh -s `which zsh`
  - name: check if oh my zsh is already installed
    stat: 
      path: ~/.oh-my-zsh
    register: ohmyzsh_check
  - name: Install ohmyzsh (please don't tell people i use this)
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    when: ohmyzsh_check.stat.exists == false

  - name: install core packages
    pacman: 
      name:
        - tmux
        - alacritty
        - picom 
        - feh 
        - i3
        - stow
        - ncdu
        - fzf 
        - git
        - firefox
        - vlc
        - nautilus
        - emacs
        - ttf-jetbrains-mono-nerd 

  - name: install neovim
    pacman: name=neovim

  - name: check if dotfiles exists 
    stat: 
      path: ~/dotfiles
    register: dotfiles_check
  - name: load in dotfiles
    ansible.builtin.git:
      repo: https://github.com/ctyler9/dotfiles.git
      dest: ~/
    when: dotfiles_check.stat.exists == false
  - name: stow dotfiles
    shell: stow ~/dotfiles


# TO-DO 
# - python, rust, go, npm
# - aur: caffeine-ng, redshift, shutter, teams-for-linux, libreoffice-still, thunderbird-beta-bin, signal-desktop, dropbox, minecraft-launcher, doom-emacs, spotify  
# - manage/download fonts (nerd font for obscure symbols)
# - download backgrounds/wallpapers and stow (dotfile config) 
# - redshift geoclue error
# - firefox takes a while to boot (graphics driver?)
#
